---
- name: Configure Firewall Rules
  hosts: all
  become: yes
  tasks:
    - name: Allow SSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow HTTP
      ufw:
        rule: allow
        port: 80

    - name: Allow HTTPS
      ufw:
        rule: allow
        port: 443

    - name: Enable firewall
      ufw:
        state: enabled
